### ISSUE TITLE
The gitlab module is no longer idempotent

### ISSUE THREAD

**Issue by blkperl** [sbadia/puppet-gitlab#172]
Due to https://github.com/alup/puppet-rbenv/issues/80 the rbenv module always triggers an event. There is a proposed patch https://github.com/alup/puppet-rbenv/pull/97 but there has been no action on it. 

I'm concerned that alup/puppet-rbenv is no longer maintained and that we should find a way to get in contact with the author, find an altertanitive module or fork our own version that works properly.

**Comment by lieutdan13** [comment]
Still running into this issue today. There has apparently been a better proposed fix for alup/puppet-rbenv#80 being alup/puppet-rbenv/pull/106. But again, the maintainer is unresponsive to the PR.

**Comment by alup** [comment]
@lieutdan13 just merged

**Comment by lieutdan13** [comment]
It appears that alup/puppet-rbenv#108 fixes this issue. Not alup/puppet-rbenv#106. I've updated my rbenv module and ran puppet on the affected machine without it producing any rbenv output.

**Comment by igalic** [comment]
@lieutdan13 they are both now merged.

**Comment by sbadia** [comment]
108, 106 and 202/204 fixed, thanks all !

**Comment by andschwa** [comment]
Nice!
