### ISSUE TITLE
Add support for Amazon Linux

### ISSUE THREAD

**Issue by JaredHatfield** [sbadia/puppet-gitlab#188]
I just tried using this puppet on Amazon Linux and it failed.

Amazon Linux reports itself with the following
```
osfamily => Linux
operatingsystem => Amazon
```

In general Amazon Linux is _fairly_ compatible with Redhat under most circumstances, but the way it reports its OS does make it incompatible with Puppet modules in some cases such as this.

**Comment by sbadia** [comment]
No answer :-( I close this issue (feel free to re-open it if you have more infos)
