### ISSUE TITLE
Add integration test suite

### ISSUE THREAD

**Issue by sroegner** [sbadia/puppet-gitlab#20]
This is software, so it needs tests.
Ideally the test suite would give a full picture of the functionality, including core gitlab concerns like project/user/key/repo management (maybe we could throw in some gitlab integration tests).

At least we want to verify that services like ssh and httpd are running (correctly)

task breakdown:

- [x] add a test task
- [x] add spec helper and a basic test, like a http check
- [ ] look into ssh-based tests
- [x] look into integrating existing gitlab tests

**Comment by sbadia** [comment]
we now use acceptance and beaker :)
https://paste.debian.net/plainh/16dd7871
