### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by eskp** [sbadia/puppet-gitlab#206]
Hi there,

Seeing this error running CentOS 6.5. System ruby is 1.8.7 and I guess this is where the problem is. Although I thought rbenv module should handle this?
I'm looking into this now but thought I'll put this here in case you've seen this. 

```
Notice: /Stage[main]/Gitlab::Install/Exec[install gitlab-shell]/returns: /home/git/gitlab-shell/bin/install:3: undefined method `require_relative' for main:Object (NoMethodError)
Error: ruby /home/git/gitlab-shell/bin/install returned 1 instead of one of [0]
Error: /Stage[main]/Gitlab::Install/Exec[install gitlab-shell]/returns: change from notrun to 0 failed: ruby /home/git/gitlab-shell/bin/install returned 1 instead of one of [0]
```

Running the script manually
```
# ruby /home/git/gitlab-shell/bin/install 
/home/git/gitlab-shell/bin/install:3: undefined method `require_relative' for main:Object (NoMethodError)
```

Cheers

**Comment by sbadia** [comment]
Hi, sorry for the delay on this issue… Your problem should be fixed in the living version of puppet-gitlab (we now use rbenv in order to pull a fresh Ruby version) Your problem seems linked to ruby 1.8.7.
