### ISSUE TITLE
/usr/local/sbin/backup-gitlab.sh won't run on CentOS 7

### ISSUE THREAD

**Issue by claflico** [sbadia/puppet-gitlab#225]
Fresh install of CentOS 7 and have just about everything working but the backups. When I try to run the backup script as the git user I get:

usr/local/sbin/backup-gitlab.sh
rake aborted!
You have already activated rake 10.1.0, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this.
/home/git/gitlab/config/boot.rb:6:in `<top (required)>'
/home/git/gitlab/config/application.rb:1:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
bundler (1.10.5)
charlock_holmes (0.6.9.4)
io-console (0.4.3)
json (1.8.1)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
test-unit (2.1.6.0)
bash-4.2$ gem uninstall rake
ERROR:  While executing gem ... (Gem::InstallError)
    gem "rake" cannot be uninstalled because it is a default gem
bash-4.2$ gem install rake
Fetching: rake-10.4.2.gem (100%)
rake's executable "rake" conflicts with /home/git/.rbenv/versions/2.1.6/bin/rake
Overwrite the executable? [yN]  y
Successfully installed rake-10.4.2
Parsing documentation for rake-10.4.2
Installing ri documentation for rake-10.4.2
Done installing documentation for rake after 2 seconds
1 gem installed
bash-4.2$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
bundler (1.10.5)
charlock_holmes (0.6.9.4)
io-console (0.4.3)
json (1.8.1)
minitest (4.7.5)
psych (2.0.5)
rake (10.4.2, 10.1.0)
rdoc (4.1.0)
test-unit (2.1.6.0)

When I try to run the backup script after that I get alot of errors about values having already been defined.

**Comment by sbadia** [comment]
hi! thanks for this bug report, it seems that rbenv is not loaded by the script, I'll fix that asap!

**Comment by sbadia** [comment]
Fixed by #226
