### ISSUE TITLE
Backup script needs claims about rake version

### ISSUE THREAD

**Issue by claudineimatos** [sbadia/puppet-gitlab#230]
Running backup script claims about rake version as we can see below:

~~~
$ /usr/local/sbin/backup-gitlab.sh
rake aborted!
You have already activated rake 10.1.0, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this.
/home/git/gitlab/config/boot.rb:6:in `<top (required)>'
/home/git/gitlab/config/application.rb:1:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
~~~

My setup versions:
~~~
Gitlab: 7.12.2
System: Centos 6.6
Puppet module: 1.0.0
~~~

Looking through the internet I've find that I can fix the problem adding `bundle exec` to the script `rake` or upgrade the rake binary at `/home/git/.rbenv/versions/2.1.6/bin/rake` which I don't known if it's safe, so I've choosed to fix the script like the little patch below:

```diff
--- /tmp/backup-gitlab.sh       2015-08-05 12:13:39.292897678 -0300
+++ /usr/local/sbin/backup-gitlab.sh    2015-08-05 12:14:12.896305122 -0300
@@ -3,5 +3,5 @@ PATH=/home/git/.rbenv/shims:/usr/local/s
 export PATH

 cd /home/git/gitlab
-rake RAILS_ENV=production gitlab:backup:create >/dev/null
+bundle exec rake RAILS_ENV=production gitlab:backup:create >/dev/null
```

What happens is that the module overwrites this script so I have two possibilities:

* Edit the template `backup-gitlab.sh.erb` 
* Add the fix to `gitlab_backup_postscript` parameter.

As I don't want to mess things up, I've choosed to add the fix to the `gitlab_backup_postscript` parameter, but in this way, the rake command will run twice, failing the first time.

So what's the best solution? upgrade rake? or change the script?

Thanks for the help!

Claudinei Matos

**Comment by sbadia** [comment]
hi @claudineimatos, many thanks for this clear bug report !!
Unfortunately this bug was [already fixed](https://github.com/sbadia/puppet-gitlab/issues/225) in master (but indeed not yet released on the puppet forge)

**Comment by sbadia** [comment]
Fixed and published on puppet forge:
* https://forgeapi.puppetlabs.com/v3/files/sbadia-gitlab-1.1.0.tar.gz
* https://github.com/sbadia/puppet-gitlab/releases/tag/v1.1.0

Thanks for the bugreport !
