### ISSUE TITLE
Support for GitLab 8

### ISSUE THREAD

**Issue by alexcern** [sbadia/puppet-gitlab#234]
Hello,

In case other people started working on it as well, I wanted to let you know that I'm making good progress on implementing support for GitLab 8, which brings many changes with CI integration and gitlab-git-http-server. It does seem possible to correctly support both 7.x and 8.x, though I may need some help to confirm it'll work fine on various 7.x versions. I expect to submit a first MR early next week.

Cheers

**Comment by sbadia** [comment]
Hi @alexcern thanks for working on this!! and sorry the the delay. Can I help on this ?

**Comment by alexcern** [comment]
Closing in favour of #236
